services:
  - type: web
    name: sis-mainways
    runtime: static
    repo: https://github.com/kofkung/SIS_Mainways
    branch: master
    buildCommand: echo "No build step required"
    staticPublishPath: .
    autoDeployTrigger: commit
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
